### ISSUE TITLE
More detailed milestones for part annotation task interface prototype

### ISSUE THREAD

**Issue by judithfan** [cogtoolslab/semantic_parts#2]
- [x] Build (scalable) "menu" of part annotation buttons that are always visible next to canvas. "Scalable" here means able to accommodate a variable number of buttons. In the case of the smiley.json data, this will include: ['head','eye','mouth','nose','Other'].
    - [x] onMouseEnter seems to be triggered at points that lie slightly outside (to the left and above) the target stroke, when aiming to click a stroke from the top left. 
    - [x] If free-response text label not "submitted," originally selected stroke appears as already annotated, and can't be selected again. Condition to un-annotate stroke if text is not properly "submitted" in the free-response window.
    - [x] Be able to load in the list of part labels from the smiley.json dictionary, b/c this is closer to what we'll be doing in the production version. 
    - [x] Re-format data output to be nested JSON dictionary, where each stroke is saved with all of its metadata in a dictionary that is nested inside an object dictionary, each of which will be written to our database. So for one sketch, the output could look something like this:

```
results = {
"smiley":
	{"svgString": "M186,65c-25.62155,0 -55.71173,-14.14414 -80,-2c-37.39381,18.6969 -50.61771,91.669 -31,126c21.84772,38.23351 86.94222,62.76445 130,52c27.06992,-6.76748 46.2058,-54.971 41,-81c-5.35635,-26.78173 -34.46828,-95 -68,-95",
	"partLabel": "face", 
	"orderSelected":0, // 0th index, b/c this was the first stroke selected
	"timeClicked":1531082660419, // time stamp of when this stroke was selected,
	"timeLabeled":1531082705874}, // time stamp of when this label was provided

	{"svgString": "M121,109c0,2.1403 -1.56044,14.43956 0,16c5.00028,5.00028 18.64011,4.71979 22,-2c5.70896,-11.41792 -23,-20.94356 -23,-10",
	"partLabel": "eye", 
	"orderSelected":1, // 1st index, b/c this was the second stroke selected
	"timeClicked":1531082802194, // time stamp of when this stroke was selected (output of Date.now())
	"timeLabeled":1531082806886}, // time stamp of when this label was provided	


	... // and so on, for each remaining stroke
}
```

- [x] Towards making this a more complete behavioral task, I've also added a few metadata elements that we'll want, e.g., RT measurements like `timeClicked` and `timeLabeled`. 
- [x] Construct trial sequence: that is, test out prototype of task where we feed in an array containing multiple "toy" sketches. Towards this, I've renamed `smiley.json` to be `data.json` and it now contains two sketches: a smiley face, and a house.
- [x] Convert task prototype into jsPsych plug-in. Let's do this as early as possible before the project grows too large in complexity, and to keep us reminded that we want to keep things fairly modular. 
    - https://www.jspsych.org/plugins/creating-a-plugin/
- [x] Test out prototype of interface on a few example *real* sketches from a real dataset... and see what the limitations are so we can figure out what needs fine-tuning, for example, see below:
- [x] Being able to select & highlight constituent splines (aka "segments") of each stroke (each of which loads as a separate Path object.
- [x] Thinking ahead to when we might even have splines that refer to multiple parts, potentially allow for "multi-label tagging" for each spline.
- [x] Might want to include an "undo" button incase participants misclick on a stroke, so that they may rectify their choice. Alternative is to allow for reselecting already tagged strokes and re-annotating them.
- [x] Adding target, distractors, and sketch history to annotation task to provide context/scaffolding to participants. (More detailed descriptions to follow post brainstorming)
- [x] save out the png rendering of the canvas after annotation
