### ISSUE TITLE
Production run to-do

### ISSUE THREAD

**Issue by hawkrobe** [cogtoolslab/semantic_parts#4]
* [x] locate sketches for all categories (in csv containing png columns, to look up on S3)
* [x] generalize menu to be properly populated with category-specific parts
* [x] test demo where each click-and-select event corresponds to a part *instance* 
  * (or populate list with `leg1`, `leg2`, etc)
* [x] decide how much data our funding can support (e.g. how many annotations each?)
* [ ] run experiment
